import React,{useCallback,useEffect,useState} from 'react';
import {ActivityIndicator,Alert,FlatList,NativeModules,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
const {ReflectionModule}=NativeModules;
const duration=ms=>`${Math.max(0,Math.round(ms/1000))}s`;
export default function ReflectionsScreen({navigation}){const insets=useSafeAreaInsets();const [query,setQuery]=useState('');const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState(null);
 const load=useCallback(()=>{setLoading(true);setError(null);ReflectionModule.getReflections(query.trim(),100,0).then(setRows).catch(()=>setError('Your reflections could not be loaded.')).finally(()=>setLoading(false));},[query]);useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t);},[load]);
 const clear=()=>Alert.alert('Clear all reflections?','This permanently deletes every saved reflection.',[{text:'Cancel',style:'cancel'},{text:'Clear all',style:'destructive',onPress:()=>ReflectionModule.clearReflections().then(load).catch(()=>setError('Could not clear reflections.'))}]);
 return <View style={[s.page,{paddingTop:Math.max(insets.top,16)}]}><View style={s.header}><Pressable onPress={()=>navigation.goBack()}><Text style={s.action}>Back</Text></Pressable><Text style={s.title}>Reflections</Text><Pressable onPress={clear} disabled={!rows.length}><Text style={[s.action,!rows.length&&s.disabled]}>Clear</Text></Pressable></View><TextInput style={s.search} placeholder="Search messages or domains" value={query} onChangeText={setQuery}/>
 {loading?<ActivityIndicator style={s.center}/>:error?<View style={s.center}><Text style={s.error}>{error}</Text><Pressable onPress={load}><Text style={s.action}>Try again</Text></Pressable></View>:!rows.length?<View style={s.center}><Text style={s.empty}>{query?'No matching reflections.':'No reflections yet.'}</Text></View>:<FlatList data={rows} keyExtractor={x=>x.id} contentContainerStyle={s.list} renderItem={({item})=><Pressable style={s.card} onPress={()=>navigation.navigate('ReflectionDetail',{id:item.id})}><Text style={s.domain}>{item.domain}</Text><Text style={s.meta}>{new Date(item.createdAtMs).toLocaleString()} · {duration(item.typingDurationMs)}</Text><Text numberOfLines={3} style={s.message}>{item.message}</Text></Pressable>}/>}</View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#F8F8F6'},header:{height:52,paddingHorizontal:22,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:20,fontWeight:'600',color:'#1A1A1A'},action:{color:'#1A1A1A',fontSize:15},disabled:{opacity:.3},search:{margin:16,paddingHorizontal:16,height:48,borderRadius:12,backgroundColor:'#FFF',color:'#1A1A1A'},center:{flex:1,alignItems:'center',justifyContent:'center',gap:16,padding:30},error:{color:'#B3261E',textAlign:'center'},empty:{color:'#757575'},list:{padding:16,gap:12},card:{padding:18,borderRadius:14,backgroundColor:'#FFF'},domain:{fontWeight:'600',color:'#1A1A1A'},meta:{fontSize:12,color:'#757575',marginTop:4},message:{fontSize:15,color:'#333',marginTop:12,lineHeight:21}});
